"""add field Rate

Revision ID: 83bb8042ba6c
Revises: 44c99189c1a0
Create Date: 2021-08-15 15:55:15.650709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83bb8042ba6c'
down_revision = '44c99189c1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote_model', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote_model', 'rate')
    # ### end Alembic commands ###
