"""add middlename to author

Revision ID: ab26c49900b9
Revises: 83bb8042ba6c
Create Date: 2021-08-22 17:10:20.867785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab26c49900b9'
down_revision = '83bb8042ba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('register_date', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'author_model', ['surname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_model', type_='unique')
    op.drop_column('author_model', 'register_date')
    # ### end Alembic commands ###
