"""add field surname

Revision ID: ca8fd0702fcd
Revises: 83bb8042ba6c
Create Date: 2021-08-15 16:00:35.586940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8fd0702fcd'
down_revision = '83bb8042ba6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('surname', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'author_model', ['surname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_model', type_='unique')
    op.drop_column('author_model', 'surname')
    # ### end Alembic commands ###
